### ISSUE TITLE
Doc request: how it works

### ISSUE THREAD

**Issue by Richie-Peak** [shoedler/crossbow#1]
There are lots of plugins that do this, it would be good to know exactly how the plugin suggests notes so that users can see whether this plugin replicates other plugins they have or compliments them.

**Comment by shoedler** [comment]
I've just released 1.1.1 including some minor fixes and tweaks. Check the new "Under the hood" section in the README, or consult [`main.ts` at `getSuggestionsInActiveEditor()`](https://github.com/shoedler/crossbow/blob/1.1.1/src/main.ts) if you're more the technical type 😉.

Also, please close this issue if this helps or get back to me via this channel if you need more info
