### ISSUE TITLE
CR: Add stop word dictionaries

### ISSUE THREAD

**Issue by Heziode** [shoedler/crossbow#17]
**Is your feature request related to a problem? Please describe.**

In the default value of `Ignored Words` there is: `image, the, always, some`.

This list is none exhaustive and can generate a lot of none pertinent relationships. For example, we have words like `with`, `instance`, etc.

Furthermore, since I am French, there is also a lot of french words that can cause none pertinent relationships, like`dans` (`in` in English), `elles` (`they` in English for women), etc.

**Describe the solution you'd like**

Add the ability to include common word (dictionary) of one or several language).

Furthermore, add a switch button, to allow case insensitive.

**Comment by kraibse** [comment]
Are you suggesting a feature to switch custom word list? Complete dictionaries would be counter-intuitive if you still want some suggestions.

If you have only a few words, you could easily paste them into the ignored words field.

**Comment by Heziode** [comment]
> Are you suggesting a feature to switch custom word list?

Nope, there is two suggestions.

1. add a "dictionary" / exhaustive list of common words (the, some, etc.
2. add a button to toggle the `Ignored Words` into case insensitive

**Comment by kraibse** [comment]
I get the second one. What's keeping you from pasting yoru words into the textbox though?

**Comment by kraibse** [comment]
Thanks for the library! I wasn't aware.

The conversion would be really easy, though. [This converter](https://regex101.com/r/UY8zFk/2) should help you with that matter.

**Comment by shoedler** [comment]
Thank you @Heziode for this request and lib suggestion -
and thank you @kraibse for triaging this and the converter. I appreciate your contributions here a lot! 

I'll look into this (especially the library) as soon as I get around to it.

**Comment by Heziode** [comment]
If you implement this feature, don’t forget to let the user to choose ONE or MORE stops word language. Beceause for non native english people (like me), we can write documents in English in addition of our native Language, or any other language.

In settings, you can do something like this:

**Stop words**:

- [ ] ar
- [X] en
- [ ] de
- [X] fr
- [ ] nl
- [ ] …

—

For a future improvement, maybe parsing a meta info in documents to apply specifc stop word dictionnaries.

Like:

```markdown
crossbow:: fr, en
−−−

# My awesome document

Ceci est un document en plusieurs langues.
```

**Comment by kraibse** [comment]
Adding to this issue, I want to remark that the performance drops very harshly after pasting in the converted lib (EN). Even to the point that editing and moving the cursor within that field takes seconds to update.

Performance is seemingly always something that keeps us devs awake at night.

**Comment by shoedler** [comment]
I've just refactored the suggestion generation and got it down from 265ms to 7ms in a large file (>50k lines) 😲.
Basically a 97% improvement. This was while using @kraibse's converted stop word list in the ignored words setting:

> Thanks for the library! I wasn't aware.
> 
> The conversion would be really easy, though. [This converter](https://regex101.com/r/UY8zFk/2) should help you with that matter.

I'm aware that this is not an ideal solution for your request. But, in your case, adding the proposed stop word list to the ignored words setting is a one-time configuration. After that you're good. Besides, I really don't want to add any language-specific restrictions (as explained in #3). That's for another plugin.

Here's an "insider" build which includes the mentioned refactorings. As a side note, this build also contains the fixes for #16 
[crossbow-1.2.1.insider3.zip](https://github.com/shoedler/crossbow/files/11523296/crossbow-1.2.1.insider3.zip)

This issue will be closed once a new release is published

**Comment by shoedler** [comment]
Added in [Release 1.3.0](https://github.com/shoedler/crossbow/releases/tag/1.3.0)

**Comment by Heziode** [comment]
Hum… not really IMHO.

The issue is about to add buildt-in a stop word dictonnary, not to performance issues raised by @kraibse

**Comment by shoedler** [comment]
You're right. It should be closed as not planned. See https://github.com/shoedler/crossbow/issues/17#issuecomment-1556031039

**Comment by Heziode** [comment]
Ok, this is more clear with a not planned ;)

If I found the time to make a PR to add this feature, will you accept it?

**Comment by shoedler** [comment]
I thought about it, and I would. But, it would have to be an **opt-in** feature.
