### ISSUE TITLE
Bug: It is can't work

### ISSUE THREAD

**Issue by YIRU69** [shoedler/crossbow#2]
Hi, friend. I love the plugin but I can't use it work.
Here is a picture. My ob version is 1.2.3
![image](https://user-images.githubusercontent.com/48148292/232228644-1124f6d5-3731-4a18-9249-fde411de2ec1.png)

**Comment by YIRU69** [comment]
I find how to solve the problem. The reason that I should open 🏹Crossbow on the ribbon. So can you add a common to show the 🏹Crossbow on the side?

**Comment by YIRU69** [comment]
Also I find a problem when I use it. Look the image. The `---` should be ignore but actually the plugin not ignore it.
![image](https://user-images.githubusercontent.com/48148292/232229571-dcab1820-5690-4713-833d-15ac7133990e.png)

**Comment by YIRU69** [comment]
Could you see the plugin? https://github.com/hadynz/obsidian-sidekick I love it. But the author leave it. The crossbow plugin have a huge problem when I use it. It have too many suggestions from I have a 3000+ notes. I just want to get a key suggestion when I use the plugin. Have you some way to solve it?

**Comment by shoedler** [comment]
Hi @YIRU69 
Thanks for pointing this out. I could add some settings which would allow you to configure the sources:
- Suggestions from filenames (Toggle)
- Suggestions from tags (Toggle)
- Suggestions from headings (Toggle)

As for your initial bug: Could you give me some steps on how to reproduce the bug you encountered?

**Comment by YIRU69** [comment]
The bug appear that I have not open the 🏹Crossbow on the side. So when I click the Crossbow on the ribbon and it appear 🏹Crossbow on the side. It is work.

**Comment by YIRU69** [comment]
thank you!
