### ISSUE TITLE
CR: Add "Folders to Ignore"

### ISSUE THREAD

**Issue by usernotnull** [shoedler/crossbow#20]
**Is your feature request related to a problem? Please describe.**
I have a lot of template files, and unfortunately many are getting picked up as suggestions

**Describe the solution you'd like**
As below:
<img width="598" alt="image" src="https://github.com/shoedler/crossbow/assets/15612814/ff3cd181-d413-4bef-a77c-3c0ad6da85ec">

**Comment by shoedler** [comment]
Great idea! I'll keep you posted via this channel once I get around to adding this.

**Comment by shoedler** [comment]
This will be added in the new release

**Comment by shoedler** [comment]
Added in [Release 1.3.0](https://github.com/shoedler/crossbow/releases/tag/1.3.0)
