### ISSUE TITLE
CR: Add Filename/Path in Suggestions

### ISSUE THREAD

**Issue by usernotnull** [shoedler/crossbow#21]
**Is your feature request related to a problem? Please describe.**

In the suggestions list, I see potential headings I could use. However it's frustrating to know where the heading is located, as I have to click on the "Go to Source" on each item to go to it.
My obsidian vault has more than a 1000 file, so with a list of 50 suggested names, each name suggestion links to files that may not even be relevant (see #20), it gets tiring.

**Describe the solution you'd like**

It's easier to skim through the suggestions if we can see the filename/path so that we quickly decide which suggestions to skip.

**Comment by shoedler** [comment]
Actually, I've implemented this while working on #16 
![image](https://github.com/shoedler/crossbow/assets/38029550/c115771b-c3a0-4299-af2c-d18becff50da)

This will be closed once a new release has been published.
Btw, as you might have already seen, you can preview these changes by using the "insider" build in https://github.com/shoedler/crossbow/issues/16#issuecomment-1555988510

**Comment by shoedler** [comment]
Added in [Release 1.3.0](https://github.com/shoedler/crossbow/releases/tag/1.3.0)
