### ISSUE TITLE
Feature Request: Exclusion of undesired suggestions

### ISSUE THREAD

**Issue by kraibse** [shoedler/crossbow#5]
Hello again,

I noticed that there is no way to exclude existing suggestions from the Crossbow list. I think it would be most user-friendly to use a context menu that opens when right-clicking an entry.

Within the context menu, there could be multiple options for excluding an item like this:
- Exclude suggestions for this line
- Exclude this suggestion (combination of actual text and backlink title)
- Allow suggestion (if previously excluded)

It would make the most sense to have a persistent archive for excluded suggestions within the Crossbow pane.

**Comment by shoedler** [comment]
Hi again
This would require too much work to implement and implies some (as you pointed out) persistant storage solution.
If you have a simple and robust idea on how to implement this I'd be happy to get your input.

**Comment by kraibse** [comment]
I just noticed that you already have a persistent solution for excluding words. It might not be per file but the global ignored words.
The exclusion option would just add that word to the textbox in the settings.

What's your take on this?
